name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: ghaction-cmake
      uses: lpenz/ghaction-cmake@v0.1
    - name: make
      run: make nufi
    - name: run-binary-help
      run: ./nufi -h
    - name: run-binary-encode
      run: ./nufi -v IE9Z54321Y -f 134217728
    - name: run-binary-decode
      run: ./nufi -d GMTT-2SQN-6FDD-6TV1
